project:
  name: Voyager CRDs
  shortName: Voyager CRDs
  url: https://github.com/voyagermesh
  description: Voyager Custom Resource Definitions
  app: Voyager crds
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: voyager-crds
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- Kubernetes 1.16+
release:
  name: voyager-crds
  namespace: voyager
