apiVersion: v1
description: Gateway Converter by AppsCode
name: gateway-converter
version: v2024.9.30
appVersion: v0.0.1
home: https://voyagermesh.com
icon: https://cdn.appscode.com/images/products/voyager/icons/android-icon-192x192.png
sources:
- https://github.com/voyagermesh
maintainers:
- name: appscode
  email: support@appscode.com
