apiVersion: v2
name: gateway-helm
description: The Helm chart for Envoy Gateway
type: application
version: v2023.9.18
appVersion: v17.0.3
maintainers:
- name: envoy-gateway-steering-committee
  url: https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
- name: envoy-gateway-maintainers
  url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS
keywords:
- gateway-api
- envoyproxy
- envoy-gateway
- eg
home: https://gateway.envoyproxy.io/
sources:
- https://github.com/envoyproxy/gateway
