apiVersion: v1
description: 'Voyager by AppsCode - Secure HAProxy Ingress Controller for Kubernetes'
name: voyager
version: v2021.04.20-beta.2
appVersion: v2021.04.20-beta.2
home: https://voyagermesh.com/
icon: https://cdn.appscode.com/images/products/voyager/icons/android-icon-192x192.png
sources:
- https://github.com/voyagermesh/voyager
maintainers:
- name: appscode
  email: support@appscode.com
