{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}

{{- $nodeSelector := .Values.nodeSelector }}
{{- if .Values.global }}
  {{ $nodeSelector = default .Values.nodeSelector .Values.global.nodeSelector }}
{{- end }}

{{- $tolerations := .Values.tolerations }}
{{- if .Values.global }}
  {{ $tolerations = default .Values.tolerations .Values.global.tolerations }}
{{- end }}

{{- $affinity := .Values.affinity }}
{{- if .Values.global }}
  {{ $affinity = default .Values.affinity .Values.global.affinity }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-converter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-converter.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway-converter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-converter.selectorLabels" . | nindent 8 }}
      annotations:
        reload: {{ randAlpha 8 }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      readinessGates:
      - conditionType: "gateway/conversion"
      {{- include "docker.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "gateway-converter.serviceAccountName" . }}
      containers:
      - name: operator
        securityContext:
          {{- toYaml .Values.server.securityContext | nindent 10 }}
        image: {{ include "server.registry" . }}/{{ .Values.server.repository }}:{{ .Values.server.tag | default .Chart.AppVersion }}
#        image: arnobkumarsaha/test
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        command:
        - /manager
        args:
        - --leader-elect
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: https
          containerPort: {{ .Values.apiserver.port }}
        - name: crd
          containerPort: 9443
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        resources:
          {{- toYaml .Values.server.resources | nindent 10 }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "gateway-converter.fullname" . }}-apiserver-cert
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or $tolerations $criticalAddon }}
      tolerations:
      {{- with $tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
    {{- if .Values.hostNetwork }}
      hostNetwork: true
    {{- end }}
