{{ template "gateway-converter.prepare-certs" $ }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-converter.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-converter.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $._caCrt }}
  tls.crt: {{ $._serverCrt }}
  tls.key: {{ $._serverKey }}