apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-converter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-converter.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  ports:
  - name: api
    port: 443
    targetPort: https
  - name: crd
    port: 9443
    targetPort: crd
  selector:
    {{- include "gateway-converter.selectorLabels" . | nindent 4 }}
