apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-converter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-converter.labels" . | nindent 4 }}
  {{- if eq .Values.monitoring.agent "prometheus.io/builtin" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
  {{- end }}
spec:
  publishNotReadyAddresses: true
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "gateway-converter.selectorLabels" . | nindent 4 }}
