{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.voyager.appscode.com
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: admission.voyager.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.voyager.appscode.com/v1beta1/admissionreviews
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - voyager.appscode.com
    apiVersions:
    - "*"
    resources:
    - "*"
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - networking.k8s.io
    apiVersions:
    - "*"
    resources:
    - ingresses
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  sideEffects: None
{{ end }}
