apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: voyager:gateway:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - gateway.networking.k8s.io
  - gateway.envoyproxy.io
  - gateway.voyagermesh.com
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: voyager:gateway:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - gateway.networking.k8s.io
  - gateway.envoyproxy.io
  - gateway.voyagermesh.com
  resources:
  - "*"
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: voyager:gateway:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - gateway.networking.k8s.io
  - gateway.envoyproxy.io
  - gateway.voyagermesh.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
